package Training.Project;

public class Elements {

	public static final String Login = "//a[@class='login']";
	public static final String Email = "email";
	public static final String Password = "passwd";
	public static final String Login_Btn = "SubmitLogin";
	public static final String Logout = "logout";
	public static final String Search_Btn = "submit_search";
	public static final String Image_Logo = "//a[@class='sf-with-ul']";
	public static final String InvalidEmailAddress = "//div[div[@class='error']]//li";
	public static final String SearchBox = "search_query_top";
	public static final String ResultsDisplayed = "//span[contains(text(),'results have been found')]";
	public static final String CreateEmail = "//label[@for='email_create']//following-sibling::input";
	public static final String CreateAccount = "//button[@id='SubmitCreate']";
	public static final String RegistrationPage = "//h1[contains(text(),'Create an account')]";
	public static final String FirstName = "//input[@id='customer_firstname']";
	public static final String LastName = "//input[@id='customer_lastname']";
	public static final String AddAddress = "//input[@id='address1']";
	public static final String City = "//input[@id='city']";
	public static final String Zipcode = "//input[@id='postcode']";
	public static final String MobileNumber = "//input[@id='phone_mobile']";
	public static final String State = "//select[@id='id_state']";
	public static final String RegisterBtn = "//button[@id='submitAccount']";
	public static final String AccountRegistered = "//h1[contains(text(),'My account')]";
//	public static final String IpodShuffle_amound = "//span[text()='$66.05']";
//	public static final String AddtoCart = "//h3//a[@title='iPod touch']/../../..//div//a[text()='Add to cart']";
//	public static final String CartDetails = "//a[contains(text(),'Cart:')]";
//	public static final String ShoppingCartSummary = "//div[@id='center_column']//h1";
//	public static final String productDescription = "//td//p[@class='s_title_block']//a";
//	public static final String SummaryAmount = "//td[@class='cart_unit']//span";
	public static final String DeleteBtn = "//a[text()='Delete']";
	public static final String ContinueShopping = "//a[@title='Continue shopping']";
	public static final String NextBtn = "//a[@title='Next']";
	public static final String AddressCheckBox ="//input[@id='addressesAreEquals']";	
	public static final String AddressNext ="processAddress";
	public static final String NewAddress= "//p[@class='address_add submit']//a[text()='Add a new address']";
	public static final String TermsAndConditionsChkBox="cgv";
	public static final String ProductDescription="//td[@class='cart_description']//p[@class='s_title_block']//a";
	public static final String ProductAmount="//td[@class='cart_unit']//span";
	public static final String payByCheque="//a[@title='Pay by cheque']";
	public static final String payByCash="//a[@title='Pay with cash on delivery (COD)']";
	public static final String SubmitPayMentBtn="//button[text()='Submit Payment']";
	public static final String ShippingNext="processCarrier";
	public static final String OrderSummary="//div//h2";
	public static final String ChequePayment="//div//h3";
	public static final String OtherPayMentModes="//a[text()='Other payment methods']";	
	public static final String ConfirmOrder="//input[@value='I confirm my order']";
	public static final String ErrorMessage="//div[@class='error']";
	public static final String SuccessMessage="//div[contains(@class,'confirmation')]";
	public static final String ShoppingCart = "//a[@title='View my shopping cart']";
	public static final String ItemDescription = "//tr[contains(@id,'product')]//p//a[contains(text(),'Printed Summer Dress')]";
	public static final String iPodShuffle = "//img[@title='Printed Dress']";
	public static final String ShuffleAddToCart = "(//a[@title='Add to cart'])[1]";
	public static final String FirstOption = "(//div[@class='product-container'])[1]";
	public static final String CloseProductWindow = "//span[@title='Close window']";
	public static final String ProceedToCheckout = "//a[@title='Proceed to checkout']";
	public static final String CartTitle = "//h1[@id='cart_title']";
	public static final String Delete = "//a[@class='cart_quantity_delete']";
	public static final String CheckBox = "//input[@id='addressesAreEquals']";
	public static final String Next2 = "//p//a[@title='Proceed to checkout']";
	public static final String Next3 = "//button//span[contains(text(),'Proceed to checkout')]";
	public static final String PayByCheck = "//a[@title='Pay by check.']";
	public static final String Submit = "//p//button[@type='submit']";
}
